name: Build Native Executable with GraalVM

on:
  push:
    branches:
      - master # 修改成你的默认分支名称
  pull_request:
    branches:
      - master # 修改成你的默认分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: ./mvnw clean package

    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        graalvm-version: '22.0.0' # 更改为所需的GraalVM版本，确保支持JDK 17

    - name: Install native-image
      run: gu install native-image

    - name: Build native executable
      run: ./mvnw -Pnative native:compile

    - name: Upload native executable
      uses: actions/upload-artifact@v2
      with:
        name: demo
        path: target/demo
