name: Build Native Executable with GraalVM

on:
  push:
    branches:
      - master # 修改成你的默认分支名称
  pull_request:
    branches:
      - master # 修改成你的默认分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      
    - name: Install Maven
      run: |
        sudo apt update
        sudo apt install -y maven

    - name: Build with Maven
      run: mvn clean package

    - name: Install native-image
      run: gu install native-image

    - name: Build native executable
      run: ./mvnw -Pnative native:compile

    - name: Upload native executable
      uses: actions/upload-artifact@v2
      with:
        name: demo
        path: target/demo
